name-template: 'Release $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: [ 'feat' ]
  - title: '🐛 Fixes'
    labels: [ 'fix', 'bug' ]
  - title: '📖 Docs'
    labels: [ 'docs' ]
  - title: '🛠️ Refactors'
    labels: [ 'refactor' ]
  - title: '🧹 Chores'
    labels: [ 'chore' ]
change-template: '- $TITLE (#$NUMBER)'
no-changes-template: 'No changes in this release.'