name-template: 'Release $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels: [ 'feat' ]
  - title: '🐛 Fixes'
    labels: [ 'fix', 'bug' ]
  - title: '📖 Docs'
    labels: [ 'docs' ]
  - title: '🛠️ Refactors'
    labels: [ 'refactor' ]
  - title: '🧹 Chores'
    labels: [ 'chore' ]

exclude-labels: []
include-labels: []
include-paths: []
exclude-contributors: []
no-contributors-template: 'No contributors'

template: |
  ## 🚀 Changes in v$NEXT_PATCH_VERSION
  
  $CHANGES