package dev.github.eventmanager.eventtypes;

public enum Performance {
    CPU_USAGE_HIGH,
    MEMORY_USAGE_HIGH,
    DISK_IO_HIGH,
    NETWORK_LATENCY_HIGH,
    THREAD_COUNT_HIGH,
    GARBAGE_COLLECTION,
    RESPONSE_TIME_SLOW,
    DATABASE_QUERY_SLOW,
    CACHE_HIT,
    CACHE_MISS,
    LOAD_AVERAGE_HIGH,
    THROUGHPUT_LOW,
    CONNECTION_POOL_EXHAUSTED,
    RESOURCE_LEAK,
    SERVICE_UNAVAILABLE,
    REQUEST_TIMEOUT,
    TRANSACTION_ROLLED_BACK,
    THREAD_DEADLOCK,
    SYSTEM_OVERLOAD,
    PERFORMANCE_DEGRADED
}