package io.github.eventmanager.eventtypes;

public enum Authentication {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_RESET_FAILURE,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
    ACCOUNT_UPDATED,
    MULTI_FACTOR_AUTH_ENABLED,
    MULTI_FACTOR_AUTH_DISABLED,
    MULTI_FACTOR_AUTH_SUCCESS,
    MULTI_FACTOR_AUTH_FAILURE,
    SESSION_STARTED,
    SESSION_ENDED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED
}