package io.github.eventmanager.eventtypes;

public enum Database {
    CONNECTION_OPENED,
    CONNECTION_CLOSED,
    QUERY_EXECUTED,
    QUERY_FAILED,
    TRANSACTION_STARTED,
    TRANSACTION_COMMITTED,
    TRANSACTION_ROLLED_BACK,
    CONNECTION_POOL_EXHAUSTED,
    CONNECTION_TIMEOUT,
    CONNECTION_RETRY,
    SCHEMA_UPDATED,
    INDEX_CREATED,
    INDEX_DROPPED,
    TABLE_CREATED,
    TABLE_DROPPED,
    ROW_INSERTED,
    ROW_UPDATED,
    ROW_DELETED,
    DATABASE_BACKUP_STARTED,
    DATABASE_BACKUP_COMPLETED
}