package io.github.eventmanager.eventtypes;

public enum Network {
    CONNECTION_ESTABLISHED,
    CONNECTION_LOST,
    DATA_RECEIVED,
    DATA_SENT,
    ERROR_OCCURRED,
    TIMEOUT,
    CONNECTION_ATTEMPT,
    CONNECTION_REFUSED,
    CONNECTION_RESET,
    CONNECTION_CLOSED,
    PACKET_LOSS,
    BANDWIDTH_LIMIT_EXCEEDED,
    NETWORK_CONGESTION,
    IP_ADDRESS_CHANGED,
    DNS_RESOLVED,
    DNS_FAILED,
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_FAILURE,
    FIREWALL_BLOCKED,
    PROXY_DETECTED
}