name: Build & Publish to JitPack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Verify Java Version
        run: java -version

      - name: Verify Gradle Java Version
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Run Tests
        run: ./gradlew test

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java Version
        run: java -version

      - name: Publish to JitPack (Trigger Build)
        run: |
          curl -X POST https://jitpack.io/com/github/TheBloodyAmateur/EventManager/1.0.5/build.log
