name: Auto Versioning

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing new tags

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 || echo 'v0.0.0')" >> $GITHUB_ENV

      - name: Determine New Version
        id: version
        uses: PaulHatch/semantic-version@v5
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"

      - name: Update `gradle.properties`
        run: |
          sed -i "s/version=.*/version=${{ steps.version.outputs.version_tag }}/" gradle.properties

      - name: Commit and Push Version Update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle.properties
          git commit -m "chore: Bump version to ${{ steps.version.outputs.version_tag }}"
          git push origin main

      - name: Create Git Tag
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin ${{ steps.version.outputs.version_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          name: "Release ${{ steps.version.outputs.version_tag }}"
          body: |
            ## Changes in this Release
            - Auto-generated release by GitHub Actions
          draft: false
          prerelease: false
