name: Release to Maven Central

on:
  push:
    tags:
      - "v*"  # Trigger release on versioned tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and Sign Artifacts
        run: ./gradlew build publishToMavenLocal
        env:
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}

      - name: Deploy with JReleaser
        run: |
          jreleaser release \
            --project-name="your-artifact-name" \
            --project-version="${{ github.ref_name }}" \
            --release-github-owner="yourusername" \
            --release-github-name="yourproject" \
            --deploy-maven-central-url="https://s01.oss.sonatype.org/service/local/" \
            --deploy-maven-central-snapshot-url="https://s01.oss.sonatype.org/content/repositories/snapshots/" \
            --deploy-maven-central-credentials-token="${{ secrets.MAVEN_CENTRAL_TOKEN }}" \
            --deploy-maven-central-signing-active=ALWAYS
        env:
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
