name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'  # Runs when you push a version tag like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v2
      - name: Import GPG Key and Verify
        run: |
          echo "$SIGNING_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - name: Publish package
        run: ./gradlew publish
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}


      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Publish to Maven Central
        run: ./gradlew publish closeAndReleaseRepository
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
